// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3mlAxEYOotj0bQD46BP7J5jO8qSO5DI',
    appId: '1:122916719132:web:589fa574b40048810b6dd9',
    messagingSenderId: '122916719132',
    projectId: 'resithon-d9ce8',
    authDomain: 'resithon-d9ce8.firebaseapp.com',
    storageBucket: 'resithon-d9ce8.appspot.com',
    measurementId: 'G-R62FPQLXXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8E1SGfePx1-Yxf_F9cc0b4m2QgmQIhg',
    appId: '1:122916719132:android:07c0bea391cff5f80b6dd9',
    messagingSenderId: '122916719132',
    projectId: 'resithon-d9ce8',
    storageBucket: 'resithon-d9ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiMLgeOWNsnOS-5HAQjMpuh-QilEgf364',
    appId: '1:122916719132:ios:2b53b90abc250ae40b6dd9',
    messagingSenderId: '122916719132',
    projectId: 'resithon-d9ce8',
    storageBucket: 'resithon-d9ce8.appspot.com',
    iosBundleId: 'com.Yahalaa.yahalaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiMLgeOWNsnOS-5HAQjMpuh-QilEgf364',
    appId: '1:122916719132:ios:c364237ce227a4530b6dd9',
    messagingSenderId: '122916719132',
    projectId: 'resithon-d9ce8',
    storageBucket: 'resithon-d9ce8.appspot.com',
    iosBundleId: 'com.resithonevent.resithonEvent.RunnerTests',
  );
}
